# 基本配置
server:
  port: 8080


spring:
  data:
    mongodb:
      host: localhost     # mongo 地址
      port: 27017         # mongo 端口号
      database: flyer
      username: admin                  # 用户名
      password: admin                  # 密码

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40c{1.} [%X{user}] : %m%n%xwEx"
